[package]
name = "tiny-tune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "4"
fern = "0"
log = "0"
chrono = "0"
 hound = "3"
midly = "0"
rodio = "0"
